feat: created customer detail page
three-consulting/epoc-frontend pull request #152
Opened 2022-05-09 12:23 UTC by ToukoH

2022-05-09 20:51 UTC, mapehe requested changes
Nice work overall, some polishing and this will be very nice!

2022-05-09 20:51 UTC, mapehe commented on components/detail/CustomerDetail.tsx
> +type CustomerDetailprops = {
You probably intended to write `CustomerDetailProps` here.

2022-05-09 20:51 UTC, mapehe commented on components/detail/CustomerDetail.tsx
> +            <Flex>Id: {id}</Flex>
I think we should not display `id` here: It's a database row id for internal use only, so it's not really relevant information for the user.

2022-05-09 20:51 UTC, mapehe commented on components/detail/CustomerDetail.tsx
> +            <Flex>Created: {created}</Flex>
Currently these are ridiculously precise (like `2022-05-03T08:39:06.557445`). It would probably suffice to just convert these to dates.

2022-05-09 20:51 UTC, mapehe commented on lib/hooks/useCustomers.ts
>  export const customerEndpointURL = `${NEXT_PUBLIC_API_URL}/customer`
For reasons I will explain later this file will probably need a `matchMutate`. Take a look at the `lib/hooks/useProjects.ts` file and look for match mutate.

You should define 
```
const projectIdEndpointCacheKeyRegex = /^\/project\/([0-9]+)$/
```
here and have the corresponding `matchMutate` for put and post hooks in this file below.

2022-05-09 20:51 UTC, mapehe commented on pages/customer/[id]/index.tsx
> +function CustomerDetailsPage({ customerId }: Props): JSX.Element {
I'd prefer this to be called `CustomerDetailPage`.

2022-05-09 20:51 UTC, mapehe commented on pages/customer/[id]/index.tsx
> +import React, { useContext } from "react"
Could you add links to these detail pages on the list that the user finds on `/customer`. Clicking on a customer on the list should open the corresponding detail page.

2022-05-11 06:32 UTC, ToukoH commented on lib/types/api.ts
> +      created?: string;
Apparently I have managed to change the type of 'created' from string to DateConstructor due to some unknown reasons. I checked the master-branch and the type of 'created' was originally a string so I reverted it.

2022-05-11 13:00 UTC, mapehe requested changes
Some very minor comments and we're all good!

2022-05-12 09:35 UTC, mapehe requested changes

2022-05-12 09:35 UTC, mapehe commented on components/detail/CustomerDetail.tsx
> +            <Flex>Created: {created && getDisplayDate(created)}</Flex>
I think it makes more sense to render
```
created && <Flex>Created: {getDisplayDate(created)}</Flex>
```

2022-05-12 10:07 UTC, mapehe reviewed
Nice work! 💎  Let's squash this to a single commit and merge.

2022-05-12 10:18 UTC, mapehe approved these changes

2022-05-12 10:18 UTC, merged